version: "3.8"

services:
  devops-portfolio:
    image: artaa/devops-portfolio-k8s:latest
    container_name: devops-portfolio
    restart: always
    ports:
      - "8080:80"
    environment:
      - PAGE_NAME=My DevOps Portfolio
      - NICK_NAME=Arta
      - LINKTREE_URL=linktr.ee/artamrj
      - NAME=Mohammadreza Javadi
      - LASTNAME_PLACE=kouchaksaraei
      - HEADER_IMAGE_URL=https://i.ibb.co/FLJ94TX0/image-5.png
      - PROFILE_IMAGE_URL=https://media.licdn.com/dms/image/v2/D4E03AQHhhPL4winPlA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1700493169537?e=1744848000&v=beta&t=ptNRF5EtTGR4ISRjg3Gh69eT16devXCKstMapwOp0NI
      - PASSWORD=sud0MakeMeASandwich
    volumes:
      - ./entrypoint.sh:/docker-entrypoint.sh
      - ./index.template.html:/usr/share/nginx/html/index.template.html
    command: ["/bin/sh", "-c", "/docker-entrypoint.sh"]

networks:
  devops-network:
    driver: bridge