apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfolio-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-portfolio-k8s
  template:
    metadata:
      labels:
        app: devops-portfolio-k8s
    spec:
      containers:
        - name: devops-portfolio-k8s
          image: artaa/devops-portfolio-k8s:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
