apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-portfolio-k8s-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-portfolio-k8s
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
